### ISSUE TITLE
Finalize docker compose ipld-eth-extractor

### ISSUE THREAD

**Issue by levlite** [vulcanize/ipld-eth-indexer#16]
ipld-eth-extractor
postgres
Our fork of geth (https://github.com/vulcanize/go-ethereum/tree/statediff_at_anyblock-1.9.11) on mainnet, rinkabey, and a local dapp testnet (https://github.com/dapphub/dapptools/blob/master/src/dapp/docs/testnet.rst).
postgraphile

**Comment by i-norden** [comment]
Closing in favor of #41
