### ISSUE TITLE
create a continuous integration environment for unit tests

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-indexer#49]
Previously, when this repo was `vulcanizedb` we had CI setup with Travis to run all unit and/or integration tests when a branch was updated or a PR was opened. We should do this again (not necessarily with TravisCI).

**Comment by ramilexe** [comment]
I think we can close this issue because we already have CI environment to run tests https://github.com/vulcanize/ipld-eth-indexer/blob/master/.github/workflows/on-pr.yaml#L13
