### ISSUE TITLE
Lift code used from here into statediffing geth and ipld-eth-server

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-indexer#84]
Move the ipld-eth-indexer packages into ipld-eth-server and deprecate this repository

**Comment by i-norden** [comment]
Statediffing geth doesn't use any code from here as an import (it would cause circular dependency issues), the code it uses has already been lifted inside

**Comment by i-norden** [comment]
We need to 

1) Move any packages from here that are being used by ipld-eth-server and aren't in statediffing geth into ipld-eth-server
2) For packages that ipld-eth-server is dependent on and which exist in both here and statediffing geth, switch the dependency to be on the statediffing geth verison
3) Deprecate/make read only this repository.

**Comment by arijitAD** [comment]
This is done in this PR https://github.com/vulcanize/ipld-eth-server/pull/92
